substitutions:
  _SERVICE_NAME: full-stack-app

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - us-west1-docker.pkg.dev/$PROJECT_ID/cloudrun/$_SERVICE_NAME:$SHORT_SHA
      - .

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - us-west1-docker.pkg.dev/$PROJECT_ID/cloudrun/$_SERVICE_NAME:$SHORT_SHA

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=us-west1-docker.pkg.dev/$PROJECT_ID/cloudrun/$_SERVICE_NAME:$SHORT_SHA
      - --region=us-west1
      - --platform=managed
      - --allow-unauthenticated
